version: "3.3"
services:
  mariadb:
    image: mariadb:11.0.2
    ports:
      - 3307:3306
    volumes:
      - bobip-mariadb-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password

  api:
    build: .
    ports:
      - 8081:8080
    environment:
      DB_PASSWORD: password
      LOG_LVL: debug
      PYTHONUNBUFFERED: 1
    depends_on:
      - mariadb
    command: bash -c "/opt/chatbot/start.sh"

  slack-bot:
    build: .
    command: python /opt/chatbot/bot.py
    environment:
      DB_PASSWORD: password
      LOG_LVL: debug
      PYTHONUNBUFFERED: 1
    volumes:
      - .:/opt/chatbot
    depends_on:
      - mariadb

volumes:
  bobip-mariadb-data:
